name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: checkout/
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          node: ${{ matrix.version }}

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy to your project."
